# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class ProvisioningState(str, Enum):

    creating = "Creating"
    updating = "Updating"
    deleting = "Deleting"
    deleted = "Deleted"
    succeeded = "Succeeded"
    failed = "Failed"


class ConfigServerBackend(str, Enum):

    not_available = "NotAvailable"
    spring_cloud_config = "SpringCloudConfig"
    azure_app_configuration = "AzureAppConfiguration"


class Platform(str, Enum):

    azure_dev_ops = "AzureDevOps"
    git_hub = "GitHub"


class AuthorizationAction(str, Enum):

    authorize = "Authorize"
    revoke = "Revoke"
    token_apply = "TokenApply"


class DebuggingKeyType(str, Enum):

    primary = "Primary"
    secondary = "Secondary"


class AppResourceProvisioningState(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"


class ArtifactType(str, Enum):

    jar = "Jar"
    docker_image = "DockerImage"


class ArtifactResourceProvisioningState(str, Enum):

    creating = "Creating"
    succeeded = "Succeeded"
    failed = "Failed"


class DeploymentResourceProvisioningState(str, Enum):

    processing = "Processing"
    succeeded = "Succeeded"
    failed = "Failed"


class DeploymentResourceStatus(str, Enum):

    starting = "Starting"
    stopping = "Stopping"
    running = "Running"


class InstanceStatus(str, Enum):

    pending = "Pending"
    running = "Running"
    succeeded = "Succeeded"
    failed = "Failed"
    unknown = "Unknown"
