# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class Resource(Model):
    """The core properties of ARM resources.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs) -> None:
        super(Resource, self).__init__(**kwargs)
        self.id = None
        self.name = None
        self.type = None


class TrackedResource(Resource):
    """The resource model definition for a ARM tracked top level resource.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    :param location: The GEO location of the resource.
    :type location: str
    :param tags: Tags of the service which is a list of key value pairs that
     describe the resource.
    :type tags: dict[str, str]
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
    }

    def __init__(self, *, location: str=None, tags=None, **kwargs) -> None:
        super(TrackedResource, self).__init__(**kwargs)
        self.location = location
        self.tags = tags


class AppClusterResource(TrackedResource):
    """App Cluster resource.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    :param location: The GEO location of the resource.
    :type location: str
    :param tags: Tags of the service which is a list of key value pairs that
     describe the resource.
    :type tags: dict[str, str]
    :param properties: Properties of the App Cluster resource
    :type properties:
     ~azure.mgmt.microservices4spring.models.ClusterResourceProperties
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': 'ClusterResourceProperties'},
    }

    def __init__(self, *, location: str=None, tags=None, properties=None, **kwargs) -> None:
        super(AppClusterResource, self).__init__(location=location, tags=tags, **kwargs)
        self.properties = properties


class ProxyResource(Resource):
    """The resource model definition for a ARM proxy resource. It will have
    everything other than required location and tags.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs) -> None:
        super(ProxyResource, self).__init__(**kwargs)


class AppResource(ProxyResource):
    """App resource payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    :param properties: Properties of the App resource
    :type properties:
     ~azure.mgmt.microservices4spring.models.AppResourceProperties
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'AppResourceProperties'},
    }

    def __init__(self, *, properties=None, **kwargs) -> None:
        super(AppResource, self).__init__(**kwargs)
        self.properties = properties


class AppResourceProperties(Model):
    """App resource properties payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param public: Indicates whether the App exposes public endpoint
    :type public: bool
    :param port: Port of the App
    :type port: int
    :ivar url: URL of the App
    :vartype url: str
    :ivar provisioning_state: Provisioning state of the App. Possible values
     include: 'Succeeded', 'Failed'
    :vartype provisioning_state: str or
     ~azure.mgmt.microservices4spring.models.AppResourceProvisioningState
    :param active_deployment_id: Azure resource Id of the active deployment of
     the App
    :type active_deployment_id: str
    """

    _validation = {
        'url': {'readonly': True},
        'provisioning_state': {'readonly': True},
    }

    _attribute_map = {
        'public': {'key': 'public', 'type': 'bool'},
        'port': {'key': 'port', 'type': 'int'},
        'url': {'key': 'url', 'type': 'str'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'active_deployment_id': {'key': 'activeDeploymentId', 'type': 'str'},
    }

    def __init__(self, *, public: bool=None, port: int=None, active_deployment_id: str=None, **kwargs) -> None:
        super(AppResourceProperties, self).__init__(**kwargs)
        self.public = public
        self.port = port
        self.url = None
        self.provisioning_state = None
        self.active_deployment_id = active_deployment_id


class ArtifactResource(ProxyResource):
    """Artifact resource payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    :param properties: Properties of the Artifact resource
    :type properties:
     ~azure.mgmt.microservices4spring.models.ArtifactResourceProperties
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'ArtifactResourceProperties'},
    }

    def __init__(self, *, properties=None, **kwargs) -> None:
        super(ArtifactResource, self).__init__(**kwargs)
        self.properties = properties


class ArtifactResourceProperties(Model):
    """Artifact resource properties payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param type: Type of the Artifact. Possible values include: 'Jar',
     'DockerImage'
    :type type: str or ~azure.mgmt.microservices4spring.models.ArtifactType
    :param java_version: Java version of the Artifact
    :type java_version: str
    :param file_name: File name of the Artifact
    :type file_name: str
    :ivar hash: Hash value of the Artifact
    :vartype hash: str
    :ivar provisioning_state: Provisioning state of the Artifact. Possible
     values include: 'Creating', 'Succeeded', 'Failed'
    :vartype provisioning_state: str or
     ~azure.mgmt.microservices4spring.models.ArtifactResourceProvisioningState
    :ivar error_message: Error message of the Artifact
    :vartype error_message: str
    :param source_location: Source location of the Artifact
    :type source_location: str
    :param version: Version of the Artifact
    :type version: str
    """

    _validation = {
        'hash': {'readonly': True},
        'provisioning_state': {'readonly': True},
        'error_message': {'readonly': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'java_version': {'key': 'javaVersion', 'type': 'str'},
        'file_name': {'key': 'fileName', 'type': 'str'},
        'hash': {'key': 'hash', 'type': 'str'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'error_message': {'key': 'errorMessage', 'type': 'str'},
        'source_location': {'key': 'sourceLocation', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
    }

    def __init__(self, *, type=None, java_version: str=None, file_name: str=None, source_location: str=None, version: str=None, **kwargs) -> None:
        super(ArtifactResourceProperties, self).__init__(**kwargs)
        self.type = type
        self.java_version = java_version
        self.file_name = file_name
        self.hash = None
        self.provisioning_state = None
        self.error_message = None
        self.source_location = source_location
        self.version = version


class ArtifactUploadDefinition(Model):
    """Artifact upload definition payload.

    :param source_location: Source location
    :type source_location: str
    :param upload_url: Upload URL
    :type upload_url: str
    """

    _attribute_map = {
        'source_location': {'key': 'sourceLocation', 'type': 'str'},
        'upload_url': {'key': 'uploadUrl', 'type': 'str'},
    }

    def __init__(self, *, source_location: str=None, upload_url: str=None, **kwargs) -> None:
        super(ArtifactUploadDefinition, self).__init__(**kwargs)
        self.source_location = source_location
        self.upload_url = upload_url


class CloudError(Model):
    """An error response from the service.

    :param error:
    :type error: ~azure.mgmt.microservices4spring.models.CloudErrorBody
    """

    _attribute_map = {
        'error': {'key': 'error', 'type': 'CloudErrorBody'},
    }

    def __init__(self, *, error=None, **kwargs) -> None:
        super(CloudError, self).__init__(**kwargs)
        self.error = error


class CloudErrorException(HttpOperationError):
    """Server responsed with exception of type: 'CloudError'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(CloudErrorException, self).__init__(deserialize, response, 'CloudError', *args)


class CloudErrorBody(Model):
    """An error response from the service.

    :param code: An identifier for the error. Codes are invariant and are
     intended to be consumed programmatically.
    :type code: str
    :param message: A message describing the error, intended to be suitable
     for display in a user interface.
    :type message: str
    :param target: The target of the particular error. For example, the name
     of the property in error.
    :type target: str
    :param details: A list of additional details about the error.
    :type details:
     list[~azure.mgmt.microservices4spring.models.CloudErrorBody]
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'details': {'key': 'details', 'type': '[CloudErrorBody]'},
    }

    def __init__(self, *, code: str=None, message: str=None, target: str=None, details=None, **kwargs) -> None:
        super(CloudErrorBody, self).__init__(**kwargs)
        self.code = code
        self.message = message
        self.target = target
        self.details = details


class ClusterResourceProperties(Model):
    """App Cluster properties payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar provisioning_state: Provisioning state of the App Cluster. Possible
     values include: 'Creating', 'Updating', 'Deleting', 'Deleted',
     'Succeeded', 'Failed'
    :vartype provisioning_state: str or
     ~azure.mgmt.microservices4spring.models.ProvisioningState
    :ivar endpoint: Endpoint of the App Cluster
    :vartype endpoint: str
    :ivar ssh_public_key: SSH Public Key of the App Cluster
    :vartype ssh_public_key: str
    :param vm_count: Virtual Machine count of the App Cluster
    :type vm_count: int
    :param vm_type: Virtual Machine type of the App Cluster
    :type vm_type: str
    :param config_server_git: Config server git properties of the App Cluster
    :type config_server_git:
     ~azure.mgmt.microservices4spring.models.ConfigServerGitProperties
    :param trace: Trace properties of the App Cluster
    :type trace: ~azure.mgmt.microservices4spring.models.TraceProperties
    :param git_authorization_list: Collection of the git authorization
     information
    :type git_authorization_list:
     list[~azure.mgmt.microservices4spring.models.GitAuthorizationProperties]
    """

    _validation = {
        'provisioning_state': {'readonly': True},
        'endpoint': {'readonly': True},
        'ssh_public_key': {'readonly': True},
    }

    _attribute_map = {
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'endpoint': {'key': 'endpoint', 'type': 'str'},
        'ssh_public_key': {'key': 'sshPublicKey', 'type': 'str'},
        'vm_count': {'key': 'vmCount', 'type': 'int'},
        'vm_type': {'key': 'vmType', 'type': 'str'},
        'config_server_git': {'key': 'configServerGit', 'type': 'ConfigServerGitProperties'},
        'trace': {'key': 'trace', 'type': 'TraceProperties'},
        'git_authorization_list': {'key': 'gitAuthorizationList', 'type': '[GitAuthorizationProperties]'},
    }

    def __init__(self, *, vm_count: int=None, vm_type: str=None, config_server_git=None, trace=None, git_authorization_list=None, **kwargs) -> None:
        super(ClusterResourceProperties, self).__init__(**kwargs)
        self.provisioning_state = None
        self.endpoint = None
        self.ssh_public_key = None
        self.vm_count = vm_count
        self.vm_type = vm_type
        self.config_server_git = config_server_git
        self.trace = trace
        self.git_authorization_list = git_authorization_list


class ConfigServerGitProperties(Model):
    """Config server git properties payload.

    All required parameters must be populated in order to send to Azure.

    :param type: Required. Type of the config server. Possible values include:
     'NotAvailable', 'SpringCloudConfig', 'AzureAppConfiguration'
    :type type: str or
     ~azure.mgmt.microservices4spring.models.ConfigServerBackend
    :param git_repositories: Required. Collection of git repositories
    :type git_repositories:
     list[~azure.mgmt.microservices4spring.models.GitRepositoryProperty]
    """

    _validation = {
        'type': {'required': True},
        'git_repositories': {'required': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'git_repositories': {'key': 'gitRepositories', 'type': '[GitRepositoryProperty]'},
    }

    def __init__(self, *, type, git_repositories, **kwargs) -> None:
        super(ConfigServerGitProperties, self).__init__(**kwargs)
        self.type = type
        self.git_repositories = git_repositories


class DebuggingKeys(Model):
    """Debugging keys payload.

    :param primary_key: Primary key
    :type primary_key: str
    :param secondary_key: Secondary key
    :type secondary_key: str
    :param primary_debugging_endpoint: Primary debugging endpoint
    :type primary_debugging_endpoint: str
    :param secondary_debugging_endpoint: Secondary debugging endpoint
    :type secondary_debugging_endpoint: str
    """

    _attribute_map = {
        'primary_key': {'key': 'primaryKey', 'type': 'str'},
        'secondary_key': {'key': 'secondaryKey', 'type': 'str'},
        'primary_debugging_endpoint': {'key': 'primaryDebuggingEndpoint', 'type': 'str'},
        'secondary_debugging_endpoint': {'key': 'secondaryDebuggingEndpoint', 'type': 'str'},
    }

    def __init__(self, *, primary_key: str=None, secondary_key: str=None, primary_debugging_endpoint: str=None, secondary_debugging_endpoint: str=None, **kwargs) -> None:
        super(DebuggingKeys, self).__init__(**kwargs)
        self.primary_key = primary_key
        self.secondary_key = secondary_key
        self.primary_debugging_endpoint = primary_debugging_endpoint
        self.secondary_debugging_endpoint = secondary_debugging_endpoint


class DeploymentInstance(Model):
    """Deployment instance payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar name: Name of the deployment instance
    :vartype name: str
    :ivar status: Status of the deployment instance. Possible values include:
     'Pending', 'Running', 'Succeeded', 'Failed', 'Unknown'
    :vartype status: str or
     ~azure.mgmt.microservices4spring.models.InstanceStatus
    :ivar reason: Failed reason of the deployment instance
    :vartype reason: str
    :ivar discovery_status: Discovery status of the deployment instance
    :vartype discovery_status: str
    """

    _validation = {
        'name': {'readonly': True},
        'status': {'readonly': True},
        'reason': {'readonly': True},
        'discovery_status': {'readonly': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'reason': {'key': 'reason', 'type': 'str'},
        'discovery_status': {'key': 'discoveryStatus', 'type': 'str'},
    }

    def __init__(self, **kwargs) -> None:
        super(DeploymentInstance, self).__init__(**kwargs)
        self.name = None
        self.status = None
        self.reason = None
        self.discovery_status = None


class DeploymentResource(ProxyResource):
    """Deployment resource payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    :param properties: Properties of the Deployment resource
    :type properties:
     ~azure.mgmt.microservices4spring.models.DeploymentResourceProperties
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'DeploymentResourceProperties'},
    }

    def __init__(self, *, properties=None, **kwargs) -> None:
        super(DeploymentResource, self).__init__(**kwargs)
        self.properties = properties


class DeploymentResourceProperties(Model):
    """Deployment resource properties payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param deployment_settings: Deployment settings of the Deployment
    :type deployment_settings:
     ~azure.mgmt.microservices4spring.models.DeploymentSettings
    :param artifact_name: Artifact name of the Deployment
    :type artifact_name: str
    :ivar provisioning_state: Provisioning state of the Deployment. Possible
     values include: 'Processing', 'Succeeded', 'Failed'
    :vartype provisioning_state: str or
     ~azure.mgmt.microservices4spring.models.DeploymentResourceProvisioningState
    :ivar status: Status of the Deployment. Possible values include:
     'Starting', 'Stopping', 'Running'
    :vartype status: str or
     ~azure.mgmt.microservices4spring.models.DeploymentResourceStatus
    :ivar active: Indicates whether the Deployment is active
    :vartype active: bool
    :ivar instances: Collection of instances belong to the Deployment
    :vartype instances:
     list[~azure.mgmt.microservices4spring.models.DeploymentInstance]
    """

    _validation = {
        'provisioning_state': {'readonly': True},
        'status': {'readonly': True},
        'active': {'readonly': True},
        'instances': {'readonly': True},
    }

    _attribute_map = {
        'deployment_settings': {'key': 'deploymentSettings', 'type': 'DeploymentSettings'},
        'artifact_name': {'key': 'artifactName', 'type': 'str'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'active': {'key': 'active', 'type': 'bool'},
        'instances': {'key': 'instances', 'type': '[DeploymentInstance]'},
    }

    def __init__(self, *, deployment_settings=None, artifact_name: str=None, **kwargs) -> None:
        super(DeploymentResourceProperties, self).__init__(**kwargs)
        self.deployment_settings = deployment_settings
        self.artifact_name = artifact_name
        self.provisioning_state = None
        self.status = None
        self.active = None
        self.instances = None


class DeploymentSettings(Model):
    """Deployment settings payload.

    :param cpu: Required CPU
    :type cpu: int
    :param memory_in_gb: Required Memory size in GB
    :type memory_in_gb: int
    :param temporary_disk: Temporary disk settings
    :type temporary_disk:
     ~azure.mgmt.microservices4spring.models.TemporaryDisk
    :param persistent_disk: Persistent disk settings
    :type persistent_disk:
     ~azure.mgmt.microservices4spring.models.PersistentDisk
    :param jvm_parameter: JVM parameter
    :type jvm_parameter: str
    :param instance_count: Instance count
    :type instance_count: int
    :param environment_variables: Collection of environment variables
    :type environment_variables: dict[str, str]
    """

    _attribute_map = {
        'cpu': {'key': 'cpu', 'type': 'int'},
        'memory_in_gb': {'key': 'memoryInGB', 'type': 'int'},
        'temporary_disk': {'key': 'temporaryDisk', 'type': 'TemporaryDisk'},
        'persistent_disk': {'key': 'persistentDisk', 'type': 'PersistentDisk'},
        'jvm_parameter': {'key': 'jvmParameter', 'type': 'str'},
        'instance_count': {'key': 'instanceCount', 'type': 'int'},
        'environment_variables': {'key': 'environmentVariables', 'type': '{str}'},
    }

    def __init__(self, *, cpu: int=None, memory_in_gb: int=None, temporary_disk=None, persistent_disk=None, jvm_parameter: str=None, instance_count: int=None, environment_variables=None, **kwargs) -> None:
        super(DeploymentSettings, self).__init__(**kwargs)
        self.cpu = cpu
        self.memory_in_gb = memory_in_gb
        self.temporary_disk = temporary_disk
        self.persistent_disk = persistent_disk
        self.jvm_parameter = jvm_parameter
        self.instance_count = instance_count
        self.environment_variables = environment_variables


class FileShareUrlResponse(Model):
    """File share URL payload.

    :param url: URL of the file share
    :type url: str
    """

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
    }

    def __init__(self, *, url: str=None, **kwargs) -> None:
        super(FileShareUrlResponse, self).__init__(**kwargs)
        self.url = url


class GetFileShareUrlRequestPayload(Model):
    """Get file share URL payload.

    All required parameters must be populated in order to send to Azure.

    :param start: Required. Start time of the file share
    :type start: datetime
    :param expiry: Required. End time of the file share
    :type expiry: datetime
    """

    _validation = {
        'start': {'required': True},
        'expiry': {'required': True},
    }

    _attribute_map = {
        'start': {'key': 'start', 'type': 'iso-8601'},
        'expiry': {'key': 'expiry', 'type': 'iso-8601'},
    }

    def __init__(self, *, start, expiry, **kwargs) -> None:
        super(GetFileShareUrlRequestPayload, self).__init__(**kwargs)
        self.start = start
        self.expiry = expiry


class GitAuthorizationProperties(Model):
    """Git authorization properties payload.

    All required parameters must be populated in order to send to Azure.

    :param git_platform: Required. Git platform. Possible values include:
     'AzureDevOps', 'GitHub'
    :type git_platform: str or
     ~azure.mgmt.microservices4spring.models.Platform
    :param action: Required. Authorization action. Possible values include:
     'Authorize', 'Revoke', 'TokenApply'
    :type action: str or
     ~azure.mgmt.microservices4spring.models.AuthorizationAction
    :param credentials: Platform credentials
    :type credentials:
     ~azure.mgmt.microservices4spring.models.PlatformCredentials
    """

    _validation = {
        'git_platform': {'required': True},
        'action': {'required': True},
    }

    _attribute_map = {
        'git_platform': {'key': 'gitPlatform', 'type': 'str'},
        'action': {'key': 'action', 'type': 'str'},
        'credentials': {'key': 'credentials', 'type': 'PlatformCredentials'},
    }

    def __init__(self, *, git_platform, action, credentials=None, **kwargs) -> None:
        super(GitAuthorizationProperties, self).__init__(**kwargs)
        self.git_platform = git_platform
        self.action = action
        self.credentials = credentials


class GitRepositoryProperty(Model):
    """Git repository property payload.

    All required parameters must be populated in order to send to Azure.

    :param repository_name: Required. Name of the repository
    :type repository_name: str
    :param uri: Required. URI of the repository
    :type uri: str
    :param label: Label of the repository
    :type label: str
    :param patterns: Collection of pattern of the repository
    :type patterns: list[str]
    :param searching_path: Searching path of the repository
    :type searching_path: list[str]
    """

    _validation = {
        'repository_name': {'required': True},
        'uri': {'required': True},
    }

    _attribute_map = {
        'repository_name': {'key': 'repositoryName', 'type': 'str'},
        'uri': {'key': 'uri', 'type': 'str'},
        'label': {'key': 'label', 'type': 'str'},
        'patterns': {'key': 'patterns', 'type': '[str]'},
        'searching_path': {'key': 'searchingPath', 'type': '[str]'},
    }

    def __init__(self, *, repository_name: str, uri: str, label: str=None, patterns=None, searching_path=None, **kwargs) -> None:
        super(GitRepositoryProperty, self).__init__(**kwargs)
        self.repository_name = repository_name
        self.uri = uri
        self.label = label
        self.patterns = patterns
        self.searching_path = searching_path


class LogSpecification(Model):
    """Specifications of the Log for Azure Monitoring.

    :param name: Name of the log
    :type name: str
    :param display_name: Localized friendly display name of the log
    :type display_name: str
    :param blob_duration: Blob duration of the log
    :type blob_duration: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'blob_duration': {'key': 'blobDuration', 'type': 'str'},
    }

    def __init__(self, *, name: str=None, display_name: str=None, blob_duration: str=None, **kwargs) -> None:
        super(LogSpecification, self).__init__(**kwargs)
        self.name = name
        self.display_name = display_name
        self.blob_duration = blob_duration


class MetricDimension(Model):
    """MetricDimension.

    :param name:
    :type name: str
    :param display_name:
    :type display_name: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
    }

    def __init__(self, *, name: str=None, display_name: str=None, **kwargs) -> None:
        super(MetricDimension, self).__init__(**kwargs)
        self.name = name
        self.display_name = display_name


class MetricSpecification(Model):
    """Specifications of the Metrics for Azure Monitoring.

    :param name: Name of the metric
    :type name: str
    :param display_name: Localized friendly display name of the metric
    :type display_name: str
    :param display_description: Localized friendly description of the metric
    :type display_description: str
    :param unit: Unit that makes sense for the metric
    :type unit: str
    :param category: Name of the metric category that the metric belongs to. A
     metric can only belong to a single category.
    :type category: str
    :param aggregation_type: Only provide one value for this field. Valid
     values: Average, Minimum, Maximum, Total, Count.
    :type aggregation_type: str
    :param supported_aggregation_types: Supported agregation types
    :type supported_aggregation_types: list[str]
    :param supported_time_grain_types: Supported time grain types
    :type supported_time_grain_types: list[str]
    :param fill_gap_with_zero: Optional. If set to true, then zero will be
     returned for time duration where no metric is emitted/published.
    :type fill_gap_with_zero: bool
    :param dimensions: Dimensions of the metric
    :type dimensions:
     list[~azure.mgmt.microservices4spring.models.MetricDimension]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'display_description': {'key': 'displayDescription', 'type': 'str'},
        'unit': {'key': 'unit', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'aggregation_type': {'key': 'aggregationType', 'type': 'str'},
        'supported_aggregation_types': {'key': 'supportedAggregationTypes', 'type': '[str]'},
        'supported_time_grain_types': {'key': 'supportedTimeGrainTypes', 'type': '[str]'},
        'fill_gap_with_zero': {'key': 'fillGapWithZero', 'type': 'bool'},
        'dimensions': {'key': 'dimensions', 'type': '[MetricDimension]'},
    }

    def __init__(self, *, name: str=None, display_name: str=None, display_description: str=None, unit: str=None, category: str=None, aggregation_type: str=None, supported_aggregation_types=None, supported_time_grain_types=None, fill_gap_with_zero: bool=None, dimensions=None, **kwargs) -> None:
        super(MetricSpecification, self).__init__(**kwargs)
        self.name = name
        self.display_name = display_name
        self.display_description = display_description
        self.unit = unit
        self.category = category
        self.aggregation_type = aggregation_type
        self.supported_aggregation_types = supported_aggregation_types
        self.supported_time_grain_types = supported_time_grain_types
        self.fill_gap_with_zero = fill_gap_with_zero
        self.dimensions = dimensions


class NameAvailability(Model):
    """Name availability result payload.

    :param name_available: Indicates whether the name is available
    :type name_available: bool
    :param reason: Reason why the name is not available
    :type reason: str
    :param message: Message why the name is not available
    :type message: str
    """

    _attribute_map = {
        'name_available': {'key': 'nameAvailable', 'type': 'bool'},
        'reason': {'key': 'reason', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }

    def __init__(self, *, name_available: bool=None, reason: str=None, message: str=None, **kwargs) -> None:
        super(NameAvailability, self).__init__(**kwargs)
        self.name_available = name_available
        self.reason = reason
        self.message = message


class NameAvailabilityParameters(Model):
    """Name availability parameters payload.

    :param type: Type of the resource to check name availability
    :type type: str
    :param name: Name to be checked
    :type name: str
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, *, type: str=None, name: str=None, **kwargs) -> None:
        super(NameAvailabilityParameters, self).__init__(**kwargs)
        self.type = type
        self.name = name


class OperationDetail(Model):
    """Operation detail payload.

    :param name: Name of the operation
    :type name: str
    :param data_action: Indicates whether the operation is a data action
    :type data_action: bool
    :param display: Display of the operation
    :type display: ~azure.mgmt.microservices4spring.models.OperationDisplay
    :param origin: Origin of the operation
    :type origin: str
    :param properties: Properties of the operation
    :type properties:
     ~azure.mgmt.microservices4spring.models.OperationProperties
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'data_action': {'key': 'dataAction', 'type': 'bool'},
        'display': {'key': 'display', 'type': 'OperationDisplay'},
        'origin': {'key': 'origin', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'OperationProperties'},
    }

    def __init__(self, *, name: str=None, data_action: bool=None, display=None, origin: str=None, properties=None, **kwargs) -> None:
        super(OperationDetail, self).__init__(**kwargs)
        self.name = name
        self.data_action = data_action
        self.display = display
        self.origin = origin
        self.properties = properties


class OperationDisplay(Model):
    """Operation display payload.

    :param provider: Resource provider of the operation
    :type provider: str
    :param resource: Resource of the operation
    :type resource: str
    :param operation: Localized friendly name for the operation
    :type operation: str
    :param description: Localized friendly description for the operation
    :type description: str
    """

    _attribute_map = {
        'provider': {'key': 'provider', 'type': 'str'},
        'resource': {'key': 'resource', 'type': 'str'},
        'operation': {'key': 'operation', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
    }

    def __init__(self, *, provider: str=None, resource: str=None, operation: str=None, description: str=None, **kwargs) -> None:
        super(OperationDisplay, self).__init__(**kwargs)
        self.provider = provider
        self.resource = resource
        self.operation = operation
        self.description = description


class OperationProperties(Model):
    """Extra Operation properties.

    :param service_specification: Service specifications of the operation
    :type service_specification:
     ~azure.mgmt.microservices4spring.models.ServiceSpecification
    """

    _attribute_map = {
        'service_specification': {'key': 'serviceSpecification', 'type': 'ServiceSpecification'},
    }

    def __init__(self, *, service_specification=None, **kwargs) -> None:
        super(OperationProperties, self).__init__(**kwargs)
        self.service_specification = service_specification


class PersistentDisk(Model):
    """Persistent disk payload.

    :param size_in_gb: Size of the persistent disk in GB
    :type size_in_gb: int
    :param mount_path: Mount path of the persistent disk
    :type mount_path: str
    """

    _validation = {
        'size_in_gb': {'maximum': 50, 'minimum': 0},
    }

    _attribute_map = {
        'size_in_gb': {'key': 'sizeInGB', 'type': 'int'},
        'mount_path': {'key': 'mountPath', 'type': 'str'},
    }

    def __init__(self, *, size_in_gb: int=None, mount_path: str=None, **kwargs) -> None:
        super(PersistentDisk, self).__init__(**kwargs)
        self.size_in_gb = size_in_gb
        self.mount_path = mount_path


class PlatformCredentials(Model):
    """Platform credentials payload.

    :param access_token: Access token
    :type access_token: str
    :param authorization_code: Authorization code
    :type authorization_code: str
    """

    _attribute_map = {
        'access_token': {'key': 'accessToken', 'type': 'str'},
        'authorization_code': {'key': 'authorizationCode', 'type': 'str'},
    }

    def __init__(self, *, access_token: str=None, authorization_code: str=None, **kwargs) -> None:
        super(PlatformCredentials, self).__init__(**kwargs)
        self.access_token = access_token
        self.authorization_code = authorization_code


class RegenerateDebuggingKeyRequestPayload(Model):
    """Regenerate debugging key request payload.

    All required parameters must be populated in order to send to Azure.

    :param key_type: Required. Type of the debugging key. Possible values
     include: 'Primary', 'Secondary'
    :type key_type: str or
     ~azure.mgmt.microservices4spring.models.DebuggingKeyType
    """

    _validation = {
        'key_type': {'required': True},
    }

    _attribute_map = {
        'key_type': {'key': 'keyType', 'type': 'str'},
    }

    def __init__(self, *, key_type, **kwargs) -> None:
        super(RegenerateDebuggingKeyRequestPayload, self).__init__(**kwargs)
        self.key_type = key_type


class ServiceBindingResource(ProxyResource):
    """Service Binding resource payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource Id for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource.
    :vartype type: str
    :param properties: Properties of the Service Binding resource
    :type properties:
     ~azure.mgmt.microservices4spring.models.ServiceBindingResourceProperties
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'ServiceBindingResourceProperties'},
    }

    def __init__(self, *, properties=None, **kwargs) -> None:
        super(ServiceBindingResource, self).__init__(**kwargs)
        self.properties = properties


class ServiceBindingResourceProperties(Model):
    """Service Binding resource properties payload.

    :param connection_string: Connection string of the Service Binding
     resource
    :type connection_string: str
    :param binding_parameters: Binding parameters of the Service Binding
     resource
    :type binding_parameters: dict[str, object]
    :param binding_type: Update time of the Service Binding resource
    :type binding_type: str
    """

    _attribute_map = {
        'connection_string': {'key': 'connectionString', 'type': 'str'},
        'binding_parameters': {'key': 'bindingParameters', 'type': '{object}'},
        'binding_type': {'key': 'bindingType', 'type': 'str'},
    }

    def __init__(self, *, connection_string: str=None, binding_parameters=None, binding_type: str=None, **kwargs) -> None:
        super(ServiceBindingResourceProperties, self).__init__(**kwargs)
        self.connection_string = connection_string
        self.binding_parameters = binding_parameters
        self.binding_type = binding_type


class ServiceSpecification(Model):
    """Service specification payload.

    :param log_specifications: Specifications of the Log for Azure Monitoring
    :type log_specifications:
     list[~azure.mgmt.microservices4spring.models.LogSpecification]
    :param metric_specifications: Specifications of the Metrics for Azure
     Monitoring
    :type metric_specifications:
     list[~azure.mgmt.microservices4spring.models.MetricSpecification]
    """

    _attribute_map = {
        'log_specifications': {'key': 'logSpecifications', 'type': '[LogSpecification]'},
        'metric_specifications': {'key': 'metricSpecifications', 'type': '[MetricSpecification]'},
    }

    def __init__(self, *, log_specifications=None, metric_specifications=None, **kwargs) -> None:
        super(ServiceSpecification, self).__init__(**kwargs)
        self.log_specifications = log_specifications
        self.metric_specifications = metric_specifications


class TemporaryDisk(Model):
    """Temporary disk payload.

    :param size_in_gb: Size of the temporary disk in GB
    :type size_in_gb: int
    :param mount_path: Mount path of the temporary disk
    :type mount_path: str
    """

    _validation = {
        'size_in_gb': {'maximum': 5, 'minimum': 0},
    }

    _attribute_map = {
        'size_in_gb': {'key': 'sizeInGB', 'type': 'int'},
        'mount_path': {'key': 'mountPath', 'type': 'str'},
    }

    def __init__(self, *, size_in_gb: int=None, mount_path: str=None, **kwargs) -> None:
        super(TemporaryDisk, self).__init__(**kwargs)
        self.size_in_gb = size_in_gb
        self.mount_path = mount_path


class TraceProperties(Model):
    """Trace properties payload.

    :param enabled: Indicates whether enable the tracing functioanlity
    :type enabled: bool
    :param app_insight_instrumentation_key: Target application insight
     instrumentation key
    :type app_insight_instrumentation_key: str
    """

    _attribute_map = {
        'enabled': {'key': 'enabled', 'type': 'bool'},
        'app_insight_instrumentation_key': {'key': 'appInsightInstrumentationKey', 'type': 'str'},
    }

    def __init__(self, *, enabled: bool=None, app_insight_instrumentation_key: str=None, **kwargs) -> None:
        super(TraceProperties, self).__init__(**kwargs)
        self.enabled = enabled
        self.app_insight_instrumentation_key = app_insight_instrumentation_key
